project:
  type: website

website:
  title: "ISSS624 Geospatial Analytics"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on_Ex1.qmd
          - text: Hands-on Exercise 2
            href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2.qmd
          - text: Hands-on Exercise 3
            href: Hands-on_Ex/Hands-on_Ex3/Hands-on_Ex3.qmd
          - text: Hands-on Exercise 4
            href: Hands-on_Ex/Hands-on_Ex4/Hands-on_Ex4.qmd
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_ex1.qmd
          - text: In-class Exercise 2
            href: In-class_Ex/In-class_Ex2/In-class_ex2.qmd
          - text: In-class Exercise 3
            href: In-class_Ex/In-class_Ex3/In-class_ex3.qmd
          - text: In-class Exercise 4
            href: In-class_Ex/In-class_Ex4/In-class_ex4.qmd
      - text: Take-Home Exercises
        menu: 
          - text: Take-Home Exercise 1
            href: Take-home_Ex/Take-home_Ex1/Take-home_Ex1.qmd
          - text: Take-Home Exercise 2
            href: Take-home_Ex/Take-home_Ex2/Take-home_Ex2.qmd
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

